2016/04/15 13:14:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php:483
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(270): CController->missingAction('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(282): CController->run('gii')
#2 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/gii
---
2016/04/15 13:19:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:19:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:19:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:19:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:19:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:19:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:19:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:24:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2016/04/15 13:46:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'yiidb'' in /var/www/html/yii/yii-1.1.17.467ff50/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/yii-1.1.17.467ff50/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CFormModel.php(39): CrudCode->init()
#6 /var/www/html/yii/yii-1.1.17.467ff50/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/yii-1.1.17.467ff50/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/crud/index
HTTP_REFERER=http://yiiproject.local/index.php/gii
---
2016/04/15 14:00:31 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/yii/yii-1.1.17.467ff50/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii/yii-1.1.17.467ff50/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii/yii-1.1.17.467ff50/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/yii-1.1.17.467ff50/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/yii-1.1.17.467ff50/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/yii-1.1.17.467ff50/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://yiiproject.local/index.php/gii
---
2016/04/15 16:25:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in /var/www/html/yii/yiiproject/protected/controllers/GoodsController.php:157
Stack trace:
#0 /var/www/html/yii/yiiproject/protected/controllers/GoodsController.php(55): GoodsController->loadModel('1')
#1 [internal function]: GoodsController->actionView('1')
#2 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(GoodsController), Array)
#3 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(GoodsController), Object(ReflectionMethod), Array)
#4 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(282): CController->run('view')
#13 /var/www/html/yii/yii-1.1.17.467ff50/framework/web/CWebApplication.php(141): CWebApplication->runController('goods/view')
#14 /var/www/html/yii/yii-1.1.17.467ff50/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/yii/yiiproject/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/goods/1
---
